[package]
name = "snapline-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
rusqlite.workspace = true
snapline-domain = { path = "../domain" }
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
